### ISSUE TITLE
500 server error on password reset page

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1040]
This is on production - https://treescount.nycgovparks.org/accounts/password/reset/

**Comment by dboyer** [comment]
Also on staging.

**Comment by hectcastro** [comment]
Relevant traceback:

```
Internal Server Error: /accounts/password/reset/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 78, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 56, in resolve_template
    return loader.get_template(template)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 162, in compile_string
    return parser.parse()
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 290, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 201, in do_extends
    nodelist = parser.parse()
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 290, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 175, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 266, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 372, in compile_filter
    return FilterExpression(token, self)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 582, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 378, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
TemplateSyntaxError: Invalid filter: 'add_class'
```
