### ISSUE TITLE
Production registration attempt failure

### ISSUE THREAD

**Issue by hectcastro** [azavea/nyc-trees#1170]
Just get an alert for this on production:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/registration/views.py", line 79, in dispatch
    return super(RegistrationView, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/registration/views.py", line 35, in post
    return self.form_valid(request, form)
  File "/usr/local/lib/python2.7/dist-packages/registration/views.py", line 82, in form_valid
    new_user = self.register(request, **form.cleaned_data)
  File "/opt/app/apps/login/backends.py", line 14, in register
    .register(request, **cleaned_data)
  File "/usr/local/lib/python2.7/dist-packages/registration/backends/default/views.py", line 91, in register
    request=request,
  File "/usr/local/lib/python2.7/dist-packages/registration/models.py", line 87, in create_inactive_user
    new_user = UserModel().objects.create_user(username, email, password)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/models.py", line 183, in create_user
    **extra_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/models.py", line 178, in _create_user
    user.save(using=self._db)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 617, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 698, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 731, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 920, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
IntegrityError: duplicate key value violates unique constraint "core_user_username_key"
```

**Comment by jwalgran** [comment]
I rolled back my dev install with ``git checkout 'develop@{2015-04-01 00:00:00}'`` but I am not having any luck sneaking a duplicate username past the validation.

My only guess right now is a race condition.

**Comment by RickMohr** [comment]
Any chance it's a case issue? Maybe try two usernames identical except for case.

**Comment by kdeloach** [comment]
Tried a few different methods but was not able to reproduce this issue.

1. Created `user1`, renamed it to `user2` in admin, and registered `user1` again.
2. Tried to register the same user with different casing, whitespace, etc.
3. Tried to replay user registration POST requests.

I would like to close this until we see it happen again in production.

**Comment by kdeloach** [comment]
Closing until we see this happen again in production.

**Comment by jwalgran** [comment]
This happened twice more:

July 24th 2015, 17:33:46.624
July 25th 2015, 20:38:17.126
