### ISSUE TITLE
Exception when AnonymousUser somehow visits /training/instructions page

### ISSUE THREAD

**Issue by hectcastro** [azavea/nyc-trees#1177]
Unclear exactly how this exception was triggered, but here is the traceback from staging last night:

```
Internal Server Error: /training/instructions
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 33, in routed
    return req_method(request, *args2, **kwargs2)
  File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 79, in wrapper
    params = callable_or_dict(request, *args, **wrapper_kwargs)
  File "/opt/app/apps/home/training/views.py", line 77, in training_instructions
    step1_complete = user.online_training_complete
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'online_training_complete'
```

**Comment by kdeloach** [comment]
You can trigger this exception by visiting `/training/instructions` while logged out. Users would typically arrive at this page by clicking an event "RSVP" button, prior to completing user training.

**Comment by RickMohr** [comment]
Examining the application logic I see no way to trigger this bug other than typing `/training/instructions` into your browser while logged out. The URL is referenced only from `apps/event/templates/event/partials/rsvp.html`, but the link is not included if the user is logged out. Closing this.

**Comment by hectcastro** [comment]
Just noting that I saw this twice over the weekend on two separate occasions.

**Comment by jwalgran** [comment]
Occurred in production Wednesday 13 May, 2015 23:48:01 UTC
