### ISSUE TITLE
Stump diameter validation error thrown but not reported to user

### ISSUE THREAD

**Issue by hectcastro** [azavea/nyc-trees#1236]
I was next to @chitchens, so I saw him getting the errors and then found them in Kibana:

```
Internal Server Error: /survey/azavea-tree-mappers/event/azavea-tree-testing-party/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/app/apps/core/decorators.py", line 32, in wrapper
    return view_fn(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 33, in routed
    return req_method(request, *args2, **kwargs2)
  File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 125, in newreq
    outp = req_function(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 106, in newreq
    outp = req_function(request, *args, **kwargs)
  File "/opt/app/apps/survey/views.py", line 421, in submit_survey_from_event
    return _create_survey_and_trees(request, event)
  File "/usr/local/lib/python2.7/dist-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/opt/app/apps/survey/views.py", line 485, in _create_survey_and_trees
    tree.clean_and_save()
  File "/opt/app/libs/mixins.py", line 21, in clean_and_save
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 1012, in full_clean
    raise ValidationError(errors)
ValidationError: {'stump_diameter': [u'Ensure this value is less than or equal to 2147483647.']}
```

**Comment by maurizi** [comment]
We may be able to sidestep this by setting a `max` attribute on all of our inputs

**Comment by kdeloach** [comment]
Double-check that we get a generic "something is wrong" error at least.

**Comment by dboyer** [comment]
I'm confirming the 24 inch limit with Parks.

**Comment by maurizi** [comment]
@dboyer I think that is a separate but related issue.  We *may* want to set a max diameter for stumps to 24", but the issue here was a exceptionally large number (2147483647") that the backend could not handle, and we should certainly not allow numbers that large.

**Comment by dboyer** [comment]
The stump diameter does not need to be limited to 24"
