### ISSUE TITLE
Type conversion error when anonymous user requests block popup content on staging

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1335]
```
Internal Server Error: /blockedge/217418/progress-page-blockedge-popup/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 33, in routed
    return req_method(request, *args2, **kwargs2)
  File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 79, in wrapper
    params = callable_or_dict(request, *args, **wrapper_kwargs)
  File "/opt/app/apps/survey/views.py", line 124, in progress_page_blockface_popup
    survey_type = _get_survey_type(blockface, request.user, group)
  File "/opt/app/apps/survey/views.py", line 135, in _get_survey_type
    .filter(blockface=blockface, user=user).current().exists()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 691, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 709, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1331, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1358, in _add_q
    current_negated=current_negated, connector=connector)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1225, in build_filter
    lookups, value)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related.py", line 1561, in get_lookup_constraint
    lookup_class(Col(alias, target, source), val), AND)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/lookups.py", line 82, in __init__
    self.rhs = self.get_prep_lookup()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_lookup(self.lookup_name, self.rhs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 646, in get_prep_lookup
    return self.get_prep_value(value)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 915, in get_prep_value
    return int(value)
TypeError: int() argument must be a string or a number, not 'SimpleLazyObject'

**Comment by jwalgran** [comment]
Can't reproduce by requesting the block edge

![screen shot 2015-04-21 at 6 14 43 pm](https://cloud.githubusercontent.com/assets/17363/7265670/5ae3a17c-e852-11e4-9265-a34b1d6a36f4.png)

**Comment by jwalgran** [comment]
Can't reproduce by clicking on the block either

![screen shot 2015-04-21 at 6 20 57 pm](https://cloud.githubusercontent.com/assets/17363/7265720/3fe54104-e853-11e4-9c13-f15f8abe8785.png)

**Comment by jwalgran** [comment]
The same error, on a different block face, came through on staging this morning:

```
Internal Server Error: /blockedge/403972/progress-page-blockedge-popup/
...
TypeError: int() argument must be a string or a number, not 'SimpleLazyObject'

**Comment by jwalgran** [comment]
It appears this only happens when a user is not logged in.

**Comment by maurizi** [comment]
@jwalgran That's really helpful info, I think I know how to fix this now
