### ISSUE TITLE
Exception in user_detail_redirect

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1440]
```
Internal Server Error: /user/profile/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 33, in routed
    return req_method(request, *args2, **kwargs2)
  File "/opt/app/apps/users/views/user.py", line 27, in user_detail_redirect
    reverse('user_detail', kwargs={'username': request.user.username}))
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 551, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 468, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))

**Comment by jwalgran** [comment]
I have not been able to reproduce this.

We could try side stepping the issue and linking directly to ``/user/{username}``

**Comment by hectcastro** [comment]
I was able to reproduce this with usernames that have unexpected characters:

- ryan.mcdurmon
- tonie@brazzley530
