### ISSUE TITLE
Event registration failure

### ISSUE THREAD

**Issue by hectcastro** [azavea/nyc-trees#1564]
Appears to be occurring on a `POST`:

```
Internal Server Error: /group/prospect-park-alliance/event/gBSmYCaSPP7rcx8wGLVdNH/register/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/app/apps/core/decorators.py", line 32, in wrapper
    return view_fn(request, *args, **kwargs)
  File "/opt/app/apps/core/decorators.py", line 69, in wrapper
    return view_fn(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 79, in wrapper
    params = callable_or_dict(request, *args, **wrapper_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 33, in routed
    return req_method(request, *args2, **kwargs2)
  File "/usr/local/lib/python2.7/dist-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/opt/app/apps/event/views.py", line 289, in register_for_event
    EventRegistration.objects.create(user=user, event=event)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 372, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 617, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 698, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 731, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 920, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
IntegrityError: duplicate key value violates unique constraint "event_eventregistration_user_id_36eab77087bfd20d_uniq"
```

**Comment by jwalgran** [comment]
https://github.com/azavea/nyc-trees/blob/master/src/nyc_trees/apps/event/views.py#L284-L298

The function is wrapped with ``transaction.atomic`` so I am not sure how we reach the ``create`` call if a person already has a registration row for the event.

**Comment by hectcastro** [comment]
Additional detail I cross-referenced using timestamps:

```json
{"tags":["django","beaver"],"@version":1,"@timestamp":"2015-05-06T13:38:48.414+00:00","host":"ip-10-0-1-132","file":"/var/log/nyc-trees-app.log","message":"DETAIL:  Key (user_id, event_id)=(1539, 29) already exists.","type":"django"}
```

**Comment by hectcastro** [comment]
Two `POSTs` to `/group/prospect-park-alliance/event/gBSmYCaSPP7rcx8wGLVdNH/register/` occurred two seconds (timestamps can't be trusted) apart from different hosts. So, I think this may just be a scenario where we need to make sure we're doing the right thing when race conditions occur.

**Comment by jwalgran** [comment]
It would be really easy to catch the integrity error and ignore it, since that is the correct logical behavior. I think that should be our plan it our attempts to replicate it don’t produce any results in a short time period.
