### ISSUE TITLE
Django statsd socket errors

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1733]
http://monitoring.treescount.nycgovparks.org:5601/#/discover?_g=(time:(from:'2015-05-26T20:55:19.390Z',mode:absolute,to:'2015-05-26T21:25:19.390Z'))&_a=(columns:!(_source),index:'logstash-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:traceback)),sort:!('@timestamp',desc))

![screen shot 2015-05-26 at 2 24 20 pm](https://cloud.githubusercontent.com/assets/17363/7823801/ff6f6674-03b2-11e5-9288-44c62a10134f.png)

```
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 185, in run
    super(Application, self).run()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 71, in run
    Arbiter(self).run()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 57, in __init__
    self.setup(app)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 113, in setup
    self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/opt/app/nyc_trees/wsgi.py", line 34, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python2.7/dist-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 87, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/django_statsd/__init__.py", line 2, in <module>
    from django_statsd import clients
  File "/usr/local/lib/python2.7/dist-packages/django_statsd/clients/__init__.py", line 28, in <module>
    _statsd = get_client()
  File "/usr/local/lib/python2.7/dist-packages/django_statsd/clients/__init__.py", line 25, in get_client
    return import_module(client).StatsClient(host, port, prefix)
  File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 138, in __init__
    host, port, 0, socket.SOCK_DGRAM

**Comment by hectcastro** [comment]
Looking at the syslog logs that overlap with the increase of these StatsD errors, it looks like private DNS queries were failing to resolve on a new instance that was trying to come up as a result of an auto scaling event (2 nodes to 4).

In this scenario, I think the health checks handled things well by never allowing the failing node into the load balancer. I'm comfortable with closing this.
