### ISSUE TITLE
Tiler processes respawned

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1734]
There was a tiler 5xx alarm from AWS at Tuesday 26 May, 2015 21:19:38 UTC

Kibana has 4 "tiler" entries around that time

/#/discover?_g=(time:(from:'2015-05-26T21:10:12.187Z',mode:absolute,to:'2015-05-26T21:40:12.188Z'))&_a=(columns:!(_source),index:'logstash-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:tiler)),sort:!('@timestamp',desc))

```javascript
{
  "_index": "logstash-2015.05.26",
  "_type": "logs",
  "_id": "AU2SF34roolW4VnYJwQC",
  "_score": null,
  "_source": {
    "@version": 1,
    "@timestamp": "2015-05-26T21:18:37.775+00:00",
    "source_host": "ip-10-0-1-63",
    "message": "May 26 21:18:37 kernel:[ 3838.466156] init: nyc-trees-tiler main process (817) terminated with status 8",
    "facility": "user",
    "severity": "warning",
    "program": "kernel",
    "processid": "-",
    "tags": [
      "syslog"
    ],
    "host": "10.0.1.63:58249"
  },
  "fields": {
    "@timestamp": [
      1432675117775
    ]
  },
  "highlight": {
    "message": [
      "May 26 21:18:37 kernel:[ 3838.466156] init: nyc-trees-@kibana-highlighted-field@tiler@/kibana-highlighted-field@ main process (817) terminated with status 8"
    ]
  },
  "sort": [
    1432675117775
  ]
}
```

```javascript
{
  "_index": "logstash-2015.05.26",
  "_type": "logs",
  "_id": "AU2SF34roolW4VnYJwQD",
  "_score": null,
  "_source": {
    "@version": 1,
    "@timestamp": "2015-05-26T21:18:37.775+00:00",
    "source_host": "ip-10-0-1-63",
    "message": "May 26 21:18:37 kernel:[ 3838.466167] init: nyc-trees-tiler main process ended, respawning",
    "facility": "user",
    "severity": "warning",
    "program": "kernel",
    "processid": "-",
    "tags": [
      "syslog"
    ],
    "host": "10.0.1.63:58249"
  },
  "fields": {
    "@timestamp": [
      1432675117775
    ]
  },
  "highlight": {
    "message": [
      "May 26 21:18:37 kernel:[ 3838.466167] init: nyc-trees-@kibana-highlighted-field@tiler@/kibana-highlighted-field@ main process ended, respawning"
    ]
  },
  "sort": [
    1432675117775
  ]
}
```

```javascript
{
  "_index": "logstash-2015.05.26",
  "_type": "logs",
  "_id": "AU2SE98roolW4VnYJuva",
  "_score": null,
  "_source": {
    "@version": 1,
    "@timestamp": "2015-05-26T21:14:40.247+00:00",
    "source_host": "ip-10-0-3-140",
    "message": "May 26 21:14:40 kernel:[18904.800543] init: nyc-trees-tiler main process (4845) terminated with status 8",
    "facility": "user",
    "severity": "warning",
    "program": "kernel",
    "processid": "-",
    "tags": [
      "syslog"
    ],
    "host": "10.0.3.140:52370"
  },
  "fields": {
    "@timestamp": [
      1432674880247
    ]
  },
  "highlight": {
    "message": [
      "May 26 21:14:40 kernel:[18904.800543] init: nyc-trees-@kibana-highlighted-field@tiler@/kibana-highlighted-field@ main process (4845) terminated with status 8"
    ]
  },
  "sort": [
    1432674880247
  ]
}
```

```javascript
{
  "_index": "logstash-2015.05.26",
  "_type": "logs",
  "_id": "AU2SE98roolW4VnYJuvb",
  "_score": null,
  "_source": {
    "@version": 1,
    "@timestamp": "2015-05-26T21:14:40.247+00:00",
    "source_host": "ip-10-0-3-140",
    "message": "May 26 21:14:40 kernel:[18904.800555] init: nyc-trees-tiler main process ended, respawning",
    "facility": "user",
    "severity": "warning",
    "program": "kernel",
    "processid": "-",
    "tags": [
      "syslog"
    ],
    "host": "10.0.3.140:52370"
  },
  "fields": {
    "@timestamp": [
      1432674880247
    ]
  },
  "highlight": {
    "message": [
      "May 26 21:14:40 kernel:[18904.800555] init: nyc-trees-@kibana-highlighted-field@tiler@/kibana-highlighted-field@ main process ended, respawning"
    ]
  },
  "sort": [
    1432674880247
  ]
}

**Comment by jwalgran** [comment]
Looks like this is happening every 15 minutes or so.

**Comment by jwalgran** [comment]
Another instance

/#/discover?_g=(time:(from:'2015-05-29T16:11:23.996Z',mode:absolute,to:'2015-05-29T16:26:23.996Z'))&_a=(columns:!(_source),index:'logstash-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:tiler)),sort:!('@timestamp',desc))

**Comment by jwalgran** [comment]
More instances of this May 29th 2015, 18:23:30.433

/#/discover?_g=(time:(from:'2015-05-29T22:16:13.073Z',mode:absolute,to:'2015-05-29T22:31:13.073Z'))&_a=(columns:!(_source),index:'logstash-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:tiler)),sort:!('@timestamp',desc))

**Comment by jwalgran** [comment]
More instances of this:
May 30th 2015, 15:19:26.159
May 30th 2015, 15:25:25.303

/#/discover?_g=(time:(from:'2015-05-30T19:12:56.469Z',mode:absolute,to:'2015-05-30T19:27:56.469Z'))&_a=(columns:!(_source),index:'logstash-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:tiler)),sort:!('@timestamp',desc))

**Comment by jwalgran** [comment]
June 2nd 2015, 10:53:47.703

/#/discover?_g=(time:(from:'2015-06-02T14:48:56.734Z',mode:absolute,to:'2015-06-02T15:03:56.734Z'))&_a=(columns:!(_source),index:'logstash-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:tiler)),sort:!('@timestamp',desc))

**Comment by hectcastro** [comment]
I think that this may be related to a race in the health check code that attempts to alter HTTP headers after they have already been sent:

```
http.js:689
    throw new Error('Can\'t set headers after they are sent.');
    ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
    at ServerResponse.res.setHeader (/opt/tiler/node_modules/windshaft/node_modules/express/node_modules/connect/lib/patch.js:62:20)
    at ServerResponse.res.header (/opt/tiler/node_modules/windshaft/node_modules/express/lib/response.js:280:8)
    at ServerResponse.res.json (/opt/tiler/node_modules/windshaft/node_modules/express/lib/response.js:135:8)
    at /opt/tiler/healthCheck.js:98:29
    at /opt/tiler/healthCheck.js:22:13
    at null.<anonymous> (/opt/tiler/node_modules/windshaft/node_modules/pg/lib/client.js:134:7)
    at g (events.js:180:16)
    at emit (events.js:117:20)
    at null.<anonymous> (/opt/tiler/node_modules/windshaft/node_modules/pg/lib/connection.js:97:12)
```

Only ever appears to happen after requests to `/health-check/`. Uncaught exception causes the process to die, and Upstart brings it back.

**Comment by jwalgran** [comment]
I suspect that two handlers are being called, either both "timeout" and "connect" or both "error" and "connect." This race could be resolved by having all the handlers check and set ``gotResponse`` not just the timeout handler.
