### ISSUE TITLE
Exception when attempting to send bulk event email

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1739]
```
/group/bronx-park-east-community-association/event/cancelled-training-530/email/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/app/apps/core/decorators.py", line 32, in wrapper
    return view_fn(request, *args, **kwargs)
  File "/opt/app/apps/core/decorators.py", line 58, in wrapper
    return view_fn(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 79, in wrapper
    params = callable_or_dict(request, *args, **wrapper_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 33, in routed
    return req_method(request, *args2, **kwargs2)
  File "/opt/app/apps/event/views.py", line 183, in event_email
    send_to(user, 'event', **msg_kwargs)
  File "/opt/app/apps/mail/libs.py", line 46, in send_to
    to = user.email
AttributeError: 'NoneType' object has no attribute 'email'

**Comment by kdeloach** [comment]
This group does not have a group admin. The workaround could be to just assign one.

**Comment by jwalgran** [comment]
Error logged again May 29th 2015, 17:30:30.120

**Comment by jwalgran** [comment]
I am going to let Parks know about the workaround.
