### ISSUE TITLE
Failure while zipping database dump on S3 - 'The read operation timed out'

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1762]
Relevant celery logs

/#/discover?_g=(time:(from:'2015-06-17T05:30:00.000Z',mode:absolute,to:'2015-06-17T05:45:00.000Z'))&_a=(columns:!(_source),index:'logstash-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'type:celery')),sort:!('@timestamp',desc))

Exception from the ``zip_dumps`` task

```
[2015-06-17 01:39:40,641: ERROR/MainProcess] Task apps.census_admin.tasks.zip_dumps[6e697556-8cd1-4d37-98b1-90711af831ac] raised unexpected: SSLError('The read operation timed out',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/app/apps/census_admin/tasks.py", line 81, in zip_dumps
    zip_f.writestr(os.path.basename(path), dump_f.read())
  File "/usr/local/lib/python2.7/dist-packages/django/core/files/base.py", line 120, in __exit__
    self.close()
  File "/usr/local/lib/python2.7/dist-packages/storages/backends/s3boto.py", line 194, in close
    self.key.close()
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 370, in close
    self.resp.read()
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 410, in read
    self._cached_response = http_client.HTTPResponse.read(self)
  File "/usr/lib/python2.7/httplib.py", line 551, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python2.7/httplib.py", line 658, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
SSLError: The read operation timed out
```

**Comment by jwalgran** [comment]
The zip task ran successfully the following day.
