### ISSUE TITLE
ProgrammingError: could not determine polymorphic type because input has type "unknown"

### ISSUE THREAD

**Issue by hectcastro** [azavea/nyc-trees#1877]
Relevant traceback:

```
Internal Server Error: /survey/detail/28107/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/app/apps/core/decorators.py", line 91, in wrapper
    return view_fn(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 33, in routed
    return req_method(request, *args2, **kwargs2)
  File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 79, in wrapper
    params = callable_or_dict(request, *args, **wrapper_kwargs)
  File "/opt/app/apps/survey/views.py", line 738, in survey_detail
    ctx = _survey_detail(request, survey_id)
  File "/opt/app/apps/survey/views.py", line 708, in _survey_detail
    'trees': json.dumps(_survey_geojson(survey, trees)),
  File "/opt/app/apps/survey/views.py", line 726, in _survey_geojson
    cursor.execute(_SURVEY_DETAIL_QUERY, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: could not determine polymorphic type because input has type "unknown"
```

Referrer for all of these appear to be `https://treescount.nycgovparks.org/admin/survey/survey/28107/?_changelist_filters=q%3D323072`.

**Comment by jwalgran** [comment]
2 more of these exceptions were logged June 10th 2016 12:31p
