### ISSUE TITLE
Provision or build-debug get "Temporary failure in name resolution" 

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#260]
Running "npm run build-debug" from command line or via "vagrant provision app":

```
vagrant ssh app -c 'cd /opt/app && npm run build-debug'

> nyc-trees@0.0.0 build-debug /opt/app
> sudo -u nyc-trees ./node_modules/.bin/gulp build --debug

[21:11:57] Using gulpfile /opt/app/gulpfile.js
[21:11:57] Starting 'build'...
[21:11:57] Starting 'clean'...
[21:11:57] Starting 'copy-fonts'...
[21:11:57] Starting 'copy-images'...
[21:11:57] Finished 'copy-fonts' after 11 ms
[21:11:57] Finished 'clean' after 23 ms
[21:11:57] Starting 'browserify'...
[21:11:57] Starting 'browserify-tests'...
[21:11:57] Rebundling test bundle JS
[21:11:57] Starting 'sass'...
[21:11:57] Starting 'vendor-css'...
[21:11:57] Finished 'copy-images' after 91 ms
[21:11:57] Starting 'copy'...
[21:11:57] Finished 'copy' after 8.32 μs
[21:11:57] Finished 'vendor-css' after 163 ms
[21:11:58] gulp-ruby-sass: directory
[21:12:02] gulp-ruby-sass: write main.css
      write main.css.map
[21:12:02] Finished 'sass' after 4.61 s
[21:12:02] Finished 'browserify' after 5.13 s
[21:12:03] Finished 'browserify-tests' after 5.35 s
[21:12:03] Starting 'copy-dev-assets'...
[21:12:03] Finished 'copy-dev-assets' after 42 ms
[21:12:03] Starting 'collect-debug'...
Traceback (most recent call last):
  File "/opt/app/manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 87, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/django_statsd/__init__.py", line 2, in <module>
    from django_statsd import clients
  File "/usr/local/lib/python2.7/dist-packages/django_statsd/clients/__init__.py", line 28, in <module>
    _statsd = get_client()
  File "/usr/local/lib/python2.7/dist-packages/django_statsd/clients/__init__.py", line 25, in get_client
    return import_module(client).StatsClient(host, port, prefix)
  File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 71, in __init__
    self._addr = (socket.gethostbyname(host), port)
socket.gaierror: [Errno -3] Temporary failure in name resolution
[21:12:03] 'collect-debug' errored after 236 ms
[21:12:03] Error in plugin 'gulp-shell'
Message:
    Command failed: Traceback (most recent call last):
  File "/opt/app/manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 87, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/django_statsd/__init__.py", line 2, in <module>
    from django_statsd import clients
  File "/usr/local/lib/python2.7/dist-packages/django_statsd/clients/__init__.py", line 28, in <module>
    _statsd = get_client()
  File "/usr/local/lib/python2.7/dist-packages/django_statsd/clients/__init__.py", line 25, in get_client
    return import_module(client).StatsClient(host, port, prefix)
  File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 71, in __init__
    self._addr = (socket.gethostbyname(host), port)
socket.gaierror: [Errno -3] Temporary failure in name resolution

Details:
    killed: false
    code: 1
    signal: null
    stdout:
    stderr: Traceback (most recent call last):
  File "/opt/app/manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 87, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/django_statsd/__init__.py", line 2, in <module>
    from django_statsd import clients
  File "/usr/local/lib/python2.7/dist-packages/django_statsd/clients/__init__.py", line 28, in <module>
    _statsd = get_client()
  File "/usr/local/lib/python2.7/dist-packages/django_statsd/clients/__init__.py", line 25, in get_client
    return import_module(client).StatsClient(host, port, prefix)
  File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 71, in __init__
    self._addr = (socket.gethostbyname(host), port)
socket.gaierror: [Errno -3] Temporary failure in name resolution

[21:12:03] 'build' errored after 5.69 s
[21:12:03] Error: [object Object]
    at formatError (/opt/app/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/opt/app/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/opt/app/node_modules/orchestrator/index.js:264:8)
    at /opt/app/node_modules/orchestrator/index.js:275:23
    at finish (/opt/app/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/opt/app/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/opt/app/node_modules/run-sequence/index.js:48:5)
    at Gulp.onError (/opt/app/node_modules/run-sequence/index.js:55:4)
    at Gulp.emit (events.js:117:20)
```

**Comment by hectcastro** [comment]
This issue was tied to the IP address of the services VM not being populated correctly by the provisioning process on Windows. The Ansible shim used in Windows/Cygwin did not appear to be escaping Ansible command line arguments correctly.
