### ISSUE TITLE
Server error when resetting password on staging

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#482]
When I try to reset my password, I get a 500 server error message.

**Comment by hectcastro** [comment]
Exception trapped from Kibana:

```
Internal Server Error: /accounts/password/reset/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/app/apps/login/views.py", line 26, in password_reset
    password_reset_form=UsernameOrEmailPasswordResetForm)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/views.py", line 163, in password_reset
    form.save(**opts)
  File "/opt/app/apps/login/forms.py", line 92, in save
    html_message=html_email)
  File "/usr/local/lib/python2.7/dist-packages/django/core/mail/__init__.py", line 56, in send_mail
    fail_silently=fail_silently)
  File "/usr/local/lib/python2.7/dist-packages/django/core/mail/__init__.py", line 38, in get_connection
    return klass(fail_silently=fail_silently, **kwds)
TypeError: __init__() got an unexpected keyword argument 'username'
```

**Comment by kdeloach** [comment]
I was able to reproduce this bug with `dboyer+2@azavea.com`. The email `dboyer@azavea.com` worked normally. I wasn't able to reproduce this issue locally.
