### ISSUE TITLE
500 server error when try to change settings on user profile page

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#633]
I tried to make my groups and contributions publicly visible and got a server error when I saved.

**Comment by hectcastro** [comment]
```
Internal Server Error: /user/settings/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 79, in wrapper
    params = callable_or_dict(request, *args, **wrapper_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 33, in routed
    return req_method(request, *args2, **kwargs2)
  File "/opt/app/apps/users/views/user.py", line 81, in update_profile_settings
    event_formset.save()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 634, in save
    return self.save_existing_objects(commit) + self.save_new_objects(commit)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 733, in save_existing_objects
    if not self.initial_forms:
  File "/usr/local/lib/python2.7/dist-packages/django/forms/formsets.py", line 173, in initial_forms
    return self.forms[:self.initial_form_count()]
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 55, in __get__
    res = instance.__dict__[self.func.__name__] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/formsets.py", line 141, in forms
    forms = [self._construct_form(i) for i in xrange(self.total_form_count())]
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 868, in _construct_form
    form = super(BaseInlineFormSet, self)._construct_form(i, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 581, in _construct_form
    pk = self.data[pk_key]
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 319, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "u'eventregistration_set-0-id'"
```

**Comment by kdeloach** [comment]
I was able to reproduce this locally.

**Comment by kdeloach** [comment]
Looks like there's a hidden field missing on this form, still troubleshooting this.

**Comment by kdeloach** [comment]
This patch fixes the bug, working on a PR now.

```
diff --git a/src/nyc_trees/apps/event/templates/event/partials/event_section.html b/src/nyc_trees/apps/event/templates/event/partials/event_section.html
index f993b5e..6b280c3 100644
--- a/src/nyc_trees/apps/event/templates/event/partials/event_section.html
+++ b/src/nyc_trees/apps/event/templates/event/partials/event_section.html
@@ -12,4 +12,5 @@
         <div class="event-action col-xs-3"></div>
     </div>
 </a>
+{% block extra_markup %}{% endblock %}
 {% endwith %}
```

**Comment by jwalgran** [comment]
@kdeloach We aren't going to push another release tonight so we can fix at our convenience.

**Comment by kdeloach** [comment]
Thanks for the heads up.

**Comment by jwalgran** [comment]
No error occurs when using the privacy popup, only the privacy tab on the settings page.
The settings are saved, so the 500 is occurring after the write to the database.

**Comment by kdeloach** [comment]
The error happens while saving the Emails tab (event email opt-ins). This happens after saving the Privacy and Account tabs.
