### ISSUE TITLE
Illegal address error exception

### ISSUE THREAD

**Issue by hectcastro** [azavea/nyc-trees#654]
Came across this exception on staging:

```
Internal Server Error: /group/nyc-parks/event/chinese-new-year-mapping-party/email/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/app/apps/core/decorators.py", line 32, in wrapper
    return view_fn(request, *args, **kwargs)
  File "/opt/app/apps/core/decorators.py", line 58, in wrapper
    return view_fn(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 79, in wrapper
    params = callable_or_dict(request, *args, **wrapper_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 33, in routed
    return req_method(request, *args2, **kwargs2)
  File "/opt/app/apps/event/views.py", line 119, in event_email
    [event.contact_email])
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/models.py", line 409, in email_user
    send_mail(subject, message, from_email, [self.email], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/mail/__init__.py", line 62, in send_mail
    return mail.send()
  File "/usr/local/lib/python2.7/dist-packages/django/core/mail/message.py", line 286, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/opt/app/apps/core/mail/backends/boto.py", line 42, in send_messages
    if self._send_message(email_message):
  File "/opt/app/apps/core/mail/backends/boto.py", line 57, in _send_message
    email_message.to)
  File "/opt/app/libs/boto_mailer.py", line 24, in send_message_bytes
    return self._connection().send_raw_email(message_bytes, from_email, to)
  File "/usr/local/lib/python2.7/dist-packages/boto/ses/connection.py", line 323, in send_raw_email
    return self._make_request('SendRawEmail', params)
  File "/usr/local/lib/python2.7/dist-packages/boto/ses/connection.py", line 119, in _make_request
    self._handle_error(response, body)
  File "/usr/local/lib/python2.7/dist-packages/boto/ses/connection.py", line 177, in _handle_error
    raise ExceptionToRaise(response.status, exc_reason, body)
SESIllegalAddressError: SESIllegalAddressError: 400 Illegal address
```

**Comment by kdeloach** [comment]
Fixed by #1617.
