### ISSUE TITLE
Remove reference to is_census_admin from Django admin

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#733]
https://github.com/azavea/nyc-trees/blob/develop/src/nyc_trees/apps/core/admin.py#L59

```
Internal Server Error: /admin/core/user/3/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 583, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 206, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 1456, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 25, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/lib/python2.7/dist-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 1393, in changeform_view
    ModelForm = self.get_form(request, obj)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/admin.py", line 77, in get_form
    return super(UserAdmin, self).get_form(request, obj, **defaults)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 670, in get_form
    % (e, self.__class__.__name__))
FieldError: Unknown field(s) (is_census_admin) specified for User. Check fields/fieldsets/exclude attributes of class NycUserAdmin.

**Comment by jwalgran** [comment]
duplicate of #731
