### ISSUE TITLE
Validation error generated 500 during treecorder testing - fix serialization

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#840]
```
Internal Server Error: /survey/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/app/apps/core/decorators.py", line 91, in wrapper
    return view_fn(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 33, in routed
    return req_method(request, *args2, **kwargs2)
  File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 125, in newreq
    outp = req_function(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 106, in newreq
    outp = req_function(request, *args, **kwargs)
  File "/opt/app/apps/survey/views.py", line 261, in submit_survey
    create_result = _create_survey_and_trees(request)
  File "/usr/local/lib/python2.7/dist-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/opt/app/apps/survey/views.py", line 337, in _create_survey_and_trees
    tree.clean_and_save()
  File "/opt/app/libs/mixins.py", line 21, in clean_and_save
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 1012, in full_clean
    raise ValidationError(errors)
ValidationError: {'status': [u'This field cannot be blank.'], 'distance_to_tree': [u'This field cannot be null.'], 'curb_location': [u'This field cannot be blank.']}

**Comment by maurizi** [comment]
This is probably due to the collapsing tree sections.

We don't serialize fields that are hidden, to prevent serializing the sections that are hidden based on tree status, but we need to handle the collapsed sections somehow (perhaps by showing the sections prior to serialization).
