### ISSUE TITLE
Tree dump to shapefile not working on staging

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#958]
The management command says the job is started but the shapefile does not appear in S3

I am getting a connection error when I try to ``celery inspect`` so I don't have more details right now.

**Comment by hectcastro** [comment]
```
[2015-03-26 13:47:14,852: ERROR/MainProcess] Task apps.census_admin.tasks.dump_trees_to_shapefile[b1827bcf-0345-44c5-887f-920c28fef7f8] raised unexpected: InternalError('line_interpolate_point: 2nd arg isnt within [0,1]\nCONTEXT:  SQL function "st_line_interpolate_point" statement 2\nPL/pgSQL function layoutboxes(geometry,boolean,double precision[],double precision[],double precision[],double precision[]) line 46 at assignment\nSQL function "layoutboxes" statement 1\n',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/app/apps/census_admin/tasks.py", line 43, in dump_trees_to_shapefile
    cursor.execute(TREES_QUERY)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 63, in execute
    return self.cursor.execute(sql)
InternalError: line_interpolate_point: 2nd arg isnt within [0,1]
CONTEXT:  SQL function "st_line_interpolate_point" statement 2
PL/pgSQL function layoutboxes(geometry,boolean,double precision[],double precision[],double precision[],double precision[]) line 46 at assignment
SQL function "layoutboxes" statement 1
```

**Comment by jwalgran** [comment]
Same error as #838
